
let all_product = [
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_1.png',
    new_price: 50.0,
    old_price: 80.5,
  },
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_2.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_3.png',
    new_price: 60.0,
    old_price: 100.5,
  },
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_4.png',
    new_price: 100.0,
    old_price: 150.0,
  },
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_5.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_6.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_7.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_8.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_9.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_10.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_11.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    category: "women",
    image: './images/product_12.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_13.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_14.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_15.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_16.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_17.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_18.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_19.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_20.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_21.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_22.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_23.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    category: "men",
    image: './images/product_24.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_25.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_26.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_27.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_28.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_29.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_30.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_31.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_32.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_33.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_34.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_35.png',
    new_price: 85.0,
    old_price: 120.5,
  },
  {
    name: "Boys Orange Colourblocked Hooded Sweatshirt",
    category: "kid",
    image: './images/product_36.png',
    new_price: 85.0,
    old_price: 120.5,
  },
];

export default all_product;
